export default [
  {
    'name' : '아두이노 자동주차 시스템',
    'info' : '',
    'disc' : '아두이노와 RC카를 결합하고, 자동으로 주차를 도와주는 시스템입니다.',
    'lang':'C언어',
    'img' : '',
    'date' : '2018.07',
    'link' : '',
  },
  {
    'name' : '스마트 블라인드',
    'info' : 'Springboot + Mysql + Mybatis + Vue.js',
    'disc' : '안전한 먹거리를 제공하는 프로젝트입니다.',
    'lang':'C언어',
    'img' : '',
    'date' : '2018.11',
    'link' : '',
  },
  {
    'name' : 'Safe_Food Project',
    'info' : 'Springboot + Mysql + Mybatis + Vue.js',
    'disc' : '안전한 먹거리를 제공하는 프로젝트입니다.',
    'lang':'Java, Springboot, Vue.js, Mybatis, Mysql',
    'img' : '',
    'date' : '2019.05',
    'link' : '',
  },
  {
    'name' : 'WebMobile Project',
    'info' : 'Springboot + Mysql + Mybatis + Vue.js',
    'disc' : 'Vue.js로 만든 글과 댓글을 작성할 수 있는 프로젝트',
    'lang':'Java, Springboot, Firebase, Vue.js',
    'img' : '',
    'date' : '2019.08',
    'link' : '',
  },
  {
    'name' : '다솜봇 카카오톡 챗봇',
    'info' : 'Node JS + API + KAKAO I OpenBuilder',
    'disc' : '여러 API를 사용하여 원하는 대답을 해주는 카카오톡 챗봇입니다.',
    'lang':'Node.Js , Firebase',
    'img' : '',
    'date' : '',
    'link' : '2019.07',
  },

]
